# Generated by Django 3.0 on 2021-06-02 13:11

from django.db import migrations
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0006_auto_20210512_1507'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='phone',
            field=phonenumber_field.modelfields.PhoneNumberField(default='0000000000', max_length=128, region=None),
        ),
    ]
