# Generated by Django 2.2.24 on 2021-06-04 05:59

from django.db import migrations, models
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0008_user_resume'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='resume',
        ),
        migrations.AddField(
            model_name='user',
            name='linkedinaccount',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='user',
            name='resumelink',
            field=models.CharField(default='https://<link-to-resume>', max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='user',
            name='phone',
            field=phonenumber_field.modelfields.PhoneNumberField(default='+000000000000', max_length=128, region=None),
        ),
    ]
